name: levantar-contenedores-de-docker
on:
  push:
    branches:
      - 'master'

jobs:
  traer_cambios:
    runs-on: self-hosted
    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false   # Desactivar la limpieza del repositorio

  levantar_contenedores:
    runs-on: self-hosted
    needs: traer_cambios
    steps:
      - name: Creando los contenedores
        run: |
          cd ${{ github.workspace }} || exit 1 # Navegar al directorio del repositorio clonado
              for archivo in *; do
              if [ -d "$archivo" ]; then
                  # Intentar cambiar al directorio
                  if cd "$archivo"; then
                      # Si se puede cambiar al directorio, ejecutar docker-compose
                      #docker-compose kill;
                      docker-compose up -d;
                      # Regresar al directorio anterior
                      cd ..
                  else
                      # Si no se puede cambiar al directorio, mostrar un mensaje de advertencia
                      echo "No se puede cambiar al directorio $archivo, omiti√©ndolo."
                  fi
              fi
          done